### ISSUE TITLE
something wrong with the artifact quest which sylvanas gives. i've placed 2 legendary boss artifacts infront of her and nothing changes

### ISSUE THREAD

**Issue by rimumba** [tdauth/wowr#813]

**Comment by tdauth** [comment]
Can you maybe post your issues on Discord instead of GitHub? https://discord.gg/eM34z36
There is a bugs channel. I usually open issues when I am sure there is an issue. Which version are you playing?
You do not have to place the boss artifacts in front of her but keep them in your hero inventory.

**Comment by tdauth** [comment]
Fixed in 2.1.
